# Generated by Django 4.1.7 on 2023-03-30 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_discount_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(blank=True, to='store.category'),
        ),
        migrations.AddField(
            model_name='product',
            name='products',
            field=models.ManyToManyField(blank=True, to='store.product'),
        ),
    ]
