version: "3.1"

services:
  backend:
    build: .
    command: daphne -b 0.0.0.0 -p 8000 core.asgi:application
#    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    expose:
      - 8000
    restart: always
    depends_on:
      - db
      - redis
    env_file:
      - .env
  db:
    image: postgres:15.0
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${SQL_USER}
      - POSTGRES_PASSWORD=${SQL_PASSWORD}
      - POSTGRES_DB=${SQL_DATABASE}
    env_file:
      - .env
    restart: unless-stopped
  redis:
    image: redis:latest
    restart: always
  celery:
    build: .
    command: celery -A core worker -l INFO
    restart: always
    volumes:
      - .:/app
    depends_on:
      - redis
  celery_beat:
    build: .
    command: celery -A core worker --beat --scheduler django --loglevel=info
    restart: always
    volumes:
      - .:/app
    depends_on:
      - redis
      - celery
  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./logs/nginx/:/app/logs/nginx/
      - ./static_files/:/app/static_files/
      - ./media/:/app/media/
    depends_on:
      - backend
    restart: always
volumes:
  postgres_data: