# Generated by Django 4.2.1 on 2023-05-18 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_email', models.EmailField(default='support@example.com', max_length=254)),
                ('orders_email', models.EmailField(default='support@example.com', max_length=254)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
