# Generated by Django 4.2 on 2023-05-01 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currency',
            name='name',
        ),
        migrations.AddField(
            model_name='currency',
            name='title',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
    ]
