# Generated by Django 4.2 on 2023-05-02 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0002_remove_currency_name_currency_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='currency',
            old_name='value',
            new_name='rate',
        ),
    ]
