# Generated by Django 4.2.1 on 2023-06-21 15:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0003_alter_currency_rate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='currency',
            old_name='symbol_left',
            new_name='symbol',
        ),
        migrations.RemoveField(
            model_name='currency',
            name='decimal_place',
        ),
        migrations.RemoveField(
            model_name='currency',
            name='symbol_right',
        ),
        migrations.RemoveField(
            model_name='currency',
            name='title',
        ),
        migrations.AlterField(
            model_name='currency',
            name='rate',
            field=models.DecimalField(decimal_places=4, default=1, max_digits=32, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
