# Generated by Django 4.2 on 2023-04-30 08:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='bookmarked_by',
            field=models.ManyToManyField(blank=True, related_name='products', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='product',
            name='bookmarks_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
