# Generated by Django 4.2 on 2023-04-06 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='rating',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Poor'), (1, 'Fair'), (2, 'Good'), (3, 'Very good'), (4, 'Excellent')], default=4),
        ),
    ]
