# Generated by Django 4.2.1 on 2023-05-31 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_product_bookmarked_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='parsing_tag',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
