# Generated by Django 4.2.1 on 2023-05-31 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_product_parsing_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='parsing_tag',
        ),
    ]
