# Generated by Django 4.2.1 on 2023-05-31 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_remove_product_parsing_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.category'),
        ),
    ]
