# Generated by Django 4.2 on 2023-04-22 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_attributegroup_alter_product_model_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='attribute',
            field=models.ManyToManyField(related_name='product', to='catalog.attribute'),
        ),
    ]
