# Generated by Django 4.2 on 2023-04-23 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_product_attribute'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='attribute',
            new_name='attributes',
        ),
        migrations.AddField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(related_name='product', to='catalog.category'),
        ),
    ]
