# Generated by Django 4.2.1 on 2023-06-07 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_product_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='bookmarks_count',
            new_name='feedbacks',
        ),
    ]
