# Generated by Django 4.2 on 2023-04-23 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_rename_attribute_product_attributes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='image',
        ),
    ]
