# Generated by Django 4.2.1 on 2023-06-21 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_rename_bookmarks_count_product_feedbacks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='bookmarked_by',
        ),
    ]
