# Generated by Django 4.2.1 on 2023-06-21 13:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0011_remove_product_bookmarked_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='bookmarked_by',
            field=models.ManyToManyField(blank=True, related_name='favorites', to=settings.AUTH_USER_MODEL),
        ),
    ]
