# Generated by Django 4.2 on 2023-04-24 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_alter_attribute_sort_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(default='', max_length=64),
        ),
    ]
