# Generated by Django 4.2.1 on 2023-06-21 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_product_bookmarked_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='bookmarked_by',
        ),
    ]
