# Generated by Django 4.2 on 2023-04-24 07:46

import core.mixins.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_alter_product_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='placeholder_small.jpg', upload_to=core.mixins.models.upload_to),
        ),
    ]
