# Generated by Django 4.2.1 on 2023-06-21 15:55

import currencies.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0004_rename_symbol_left_currency_symbol_and_more'),
        ('catalog', '0015_alter_product_favorites'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='model',
        ),
        migrations.AddField(
            model_name='product',
            name='currency',
            field=models.ForeignKey(default=currencies.models.Currency.get_default_id, on_delete=django.db.models.deletion.PROTECT, to='currencies.currency'),
        ),
    ]
