# Generated by Django 4.2 on 2023-04-26 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='date_end',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='date_start',
            field=models.DateTimeField(),
        ),
    ]
