# Generated by Django 4.2 on 2023-04-04 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Enabled'), (1, 'Disabled')], default=0),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Enabled'), (1, 'Disabled')], default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='invoice_prefix',
            field=models.CharField(default='', max_length=16),
        ),
    ]
